"""empty message

Revision ID: 3abf3b8c833b
Revises: 7b1f0f92005b
Create Date: 2022-07-26 04:44:58.389651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abf3b8c833b'
down_revision = '7b1f0f92005b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')
    op.alter_column('todolists','completed', nullable =False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
