"""empty message

Revision ID: 3e4f1ca449c0
Revises: 70cb02795c73
Create Date: 2022-07-24 16:04:56.576175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4f1ca449c0'
down_revision = '70cb02795c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE persons SET completed = False WHERE completed IS NULL;')
    
    op.alter_column('persons', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'completed')
    # ### end Alembic commands ###
